### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by OndrejNepozitek** [OndrejNepozitek/ProceduralLevelGenerator#50]
- [ ] Make the Unity plugin compatible with the new DungeonGenerator
- [ ] Make it easy to export map descriptions from the Unity plugin
- [ ] Make it possible to forbid individual room templates to repeat in the level
